enabled: true

lobby:
  teleport-players-to-lobby-on-join: true
  set-gamemode-on-join: ADVENTURE

chat:
  per-game-chat: true

commands:
  no-permission: "&4You do not have permission to do this!"

  sg:
    zero-arguments: "&ePlease use &b'/sg help' &eto see all command options!"
    specify-game: "&4Please specify the game name!"
    game-does-not-exist: "&4The game [%game%] does not exist!"
    already-in-game: "&4You are already in a game!"
    not-in-game: "&4You are currently not in a game!"
  sgadmin:
    zero-arguments: "&ePlease use &b'/sgadmin help' &eto see all command options!"
    set-lobby-spawn: "&2The set spawn lobby sub-command is not supported by the console!"
    chests-restocked: "&2You have restocked the chests in [%game%]!"
    specify-game-to-remove: "&4Please specify the game you would like to remove!"
    game-removed: "&2You have removed the game [%game%]!"

events:
  game:
    waiting-countdown: 15
    starting-countdown: 5
    attempting-start: "&2&lAttempting to start the game..."
    insufficient-players: "&eNot enough players to start game! Waiting again..."
    waiting-game-countdown: "&eStarting game in &2%count%"
    starting-message: " \n&bWelcome to Survival Games! Have fun.\n "
    starting-game-countdown: "&ePrepare to run in &4%count%&e!"
    start-message: "&2&lGO GO GO"

    chest-restock: "&2All Chests have been restocked!"

    player-returning-error: "&4 You cannot return to this game once left!"
    not-joinable-error: "&4This game is currently not joinable!"
    full-game-error: "&4The game you are trying to join is full!"

    player-join: "&b[%player_count%/%max_players%] &2%player% &ehas joined the game!"
    player-leave: "&2%player% &ehas left the game!"

    player-killed: "&a%player% &7was killed by &4%killer%"
    player-killed-receiver: "&d-----------------------------\n             &a&lYou Died!\n \n&r&eUse /sg leave to leave the game \n \n&d-----------------------------"
    player-died: "&4%player% &ehas died!"

chests:
  restock-time: 10
  max-items-in-chest: 6
  min-items-in-chest: 3
  items:
    1:
      material: DIRT
      amount: 12
      probability: 80
    2:
      material: DIAMOND_SWORD
      amount: 1
      probability: 20
      enchantments:
        - DAMAGE_ALL;3
        - DURABILITY;1